### DISCUSSION TITLE
Question about Scaleway provider

### DISCUSSION THREAD

**Discussion by vdeville** [klausmeyer/docker-registry-browser#703] [Q&A]
Hello,
I can't get your tool to work with Scaleway's container registry. Has anyone tried it yet?
Registration and usage is free if you want to try wiht this provider
Thanks

**Comment by klausmeyer** [comment]
Hi @vdeville,

I personally haven't used Scaleway before and also don't know their registry.

Feel free to provide some logs of the application talking to your Scaleway registry (with sensible details redacted of course) and I will have a look. Maybe it's just a small thing and we can make it work (but I can't promise anything).

**Comment by vdeville** [comment]
Hello,

I'm not abble to get lot of logs, at this time is what i see:

my docker compose:
```yaml
services:
  registry-browser:
    image: klausmeyer/docker-registry-browser
    ports:
      - "8080:8080"
    environment:
      ENABLE_DELETE_IMAGES: true
      DOCKER_REGISTRY_URL: https://rg.fr-par.scw.cloud/
      SECRET_KEY_BASE: c164d32b889ae.........1ccc959
      REGISTRY_LOG_LEVEL: 3
      REGISTRY_LOG_HEADERS: 1
      TOKEN_AUTH_USER: nouser
      TOKEN_AUTH_PASSWORD: XXXX
```

In the web interface:
![Capture d’écran 2024-12-31 à 13 54 15](https://github.com/user-attachments/assets/a5012267-f0f4-452d-a792-008dc2ff85ea)

In the logs:
```
registry-browser-1  | Puma starting in single mode...
registry-browser-1  | * Puma version: 6.4.3 (ruby 3.3.5-p100) ("The Eagle of Durango")
registry-browser-1  | *  Min threads: 3
registry-browser-1  | *  Max threads: 3
registry-browser-1  | *  Environment: production
registry-browser-1  | *          PID: 1
registry-browser-1  | * Listening on http://0.0.0.0:8080
registry-browser-1  | Use Ctrl-C to stop
registry-browser-1  | I, [2024-12-31T12:51:08.878075 #1]  INFO -- : [4c2a672f-e106-483c-bae1-e77394d6bdf1] Started GET "/" for 192.168.4.1 at 2024-12-31 12:51:08 +0000
registry-browser-1  | I, [2024-12-31T12:51:08.880385 #1]  INFO -- : [4c2a672f-e106-483c-bae1-e77394d6bdf1] Processing by RepositoriesController#index as HTML
registry-browser-1  | I, [2024-12-31T12:51:08.889476 #1]  INFO -- request: [4c2a672f-e106-483c-bae1-e77394d6bdf1] GET https://rg.fr-par.scw.cloud/v2/_catalog?n=100
registry-browser-1  | I, [2024-12-31T12:51:08.889541 #1]  INFO -- request: [4c2a672f-e106-483c-bae1-e77394d6bdf1] User-Agent: "Faraday v2.12.0"
registry-browser-1  | Authorization: "bearer XXXX_REPLACED_XXX"
registry-browser-1  | I, [2024-12-31T12:51:08.958762 #1]  INFO -- : [4c2a672f-e106-483c-bae1-e77394d6bdf1]   Rendered layout layouts/application.html.erb (Duration: 6.5ms | GC: 0.0ms)
registry-browser-1  | I, [2024-12-31T12:51:08.958899 #1]  INFO -- : [4c2a672f-e106-483c-bae1-e77394d6bdf1] Completed 200 OK in 78ms (Views: 9.2ms | GC: 0.1ms)
```

Thanks
