### ISSUE TITLE
Using a docker secret file in an environment variable

### ISSUE THREAD

**Issue by ozlerhakan** [klausmeyer/docker-registry-browser#11]
Hi @klausmeyer ,

In the readme it says that  `You can also set BASIC_AUTH_USER and BASIC_AUTH_PASSWORD as Docker Swarm secrets.` Apparently, when i specify a password file created with docker secret in a stack file like below, the app cannot connect to the registry. the password string is not read from the mentioned file (`/run/secrets/registry-pwd`). Do you know any other approach for that?

```
...
  registryui:
    image: klausmeyer/docker-registry-browser
    ...
    secrets:
      - source: registry-v2-pwd 
        target: registry-pwd 
        mode: 0440
    networks:
      - registry-proxy
      - registry-ui
    environment:
      - DOCKER_REGISTRY_URL=https://example.com
      - BASIC_AUTH_USER=hakan
      - BASIC_AUTH_PASSWORD=/run/secrets/registry-pwd
```

**Comment by klausmeyer** [comment]
Looks like the readme isn't descriptive enough - sorry about that.

The secret needs to be called `BASIC_AUTH_PASSWORD` (and available at `/run/secrets/BASIC_AUTH_PASSWORD` inside the container). The application reads it instead of the environment-variable with the same name.

**Comment by ozlerhakan** [comment]
Thank you @klausmeyer , after editing the stack file as follows , it works well

```
...
  registryui:
    image: klausmeyer/docker-registry-browser
    ...
    secrets:
      - source: registry-v2-pwd 
        target: BASIC_AUTH_PASSWORD 
        mode: 0444
    networks:
      - registry-proxy
      - registry-ui
    environment:
      - DOCKER_REGISTRY_URL=https://example.com
      - BASIC_AUTH_USER=hakan
```
PS. the new secret file also needed to be changed the file mode from 0440 to 0444.
