### ISSUE TITLE
Traefik Reverse Proxy repo/ redirect

### ISSUE THREAD

**Issue by johnluetke** [klausmeyer/docker-registry-browser#320]
I'm getting a redirect error when trying to run the app behind a Traefik reverse proxy. I've read #303 and #179 and have had no luck in figuring this out.

When I access `http://docker-registry-browser/docker`, I get redirected to `http://docker-registry-browser/repo/docker`, which 404s

I'm setting the `RAILS_RELATIVE_URL_ROOT` and `SCRIPT_NAME` environment vars to my desired subpath:

```
environment:
      DOCKER_REGISTRY_URL: ***
      RAILS_RELATIVE_URL_ROOT: /docker
      SCRIPT_NAME: /docker
```

And have my reverse proxy listening on the `/docker/` path

```
deploy:
     labels:
       ...
       - "traefik.http.routers.docker-registry-browser.rule=Host(`docker-registry-browser`) && PathPrefix(`/docker/`)"
```

I acknowledge that this is most likely an issue with my Traefik configuration, but where is the `/repo/` path coming from? Without any subpath configuration, it is not a part of the resolved URL, which loads the app correctly.

**Comment by klausmeyer** [comment]
Hi @johnluetke,

I had a look and was able to reproduce.

Problem is that traefik by default also sends that configured `PathPrefix` to the backend service.
You can use a middleware to remove this prefix again:

```yaml
- 'traefik.http.middlewares.browser-stripprefix.stripprefix.prefixes=/docker'
- 'traefik.http.routers.browser.rule=PathPrefix(`/docker`)'
- 'traefik.http.routers.browser.middlewares=browser-stripprefix@docker'
```

My complete working example:

```yaml
version: '3'

services:

  traefik:
    image: traefik:v2.3
    command:
      - '--providers.docker=true'
      - '--entryPoints.web.address=:80'
      - '--providers.docker.watch=true'
      - '--providers.docker.swarmmode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '80:80'
      - '8081:8080'
    deploy:
      labels:
        - traefik.enable=true

  registry:
    image: registry:2
    ports:
      - 5000:5000

  browser:
    image: klausmeyer/docker-registry-browser:latest
    environment:
      DOCKER_REGISTRY_URL: http://registry:5000
      RAILS_RELATIVE_URL_ROOT: /docker
      SCRIPT_NAME: /docker
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.middlewares.browser-stripprefix.stripprefix.prefixes=/docker'
        - 'traefik.http.routers.browser.rule=PathPrefix(`/docker`)'
        - 'traefik.http.routers.browser.middlewares=browser-stripprefix@docker'
        - 'traefik.http.routers.browser.service=browser'
        - 'traefik.http.services.browser.loadbalancer.server.port=8080'
```

Please let me know if that helped with your issue.

**Comment by johnluetke** [comment]
This is embarrassing 🙃

Thanks for your time @klausmeyer

**Comment by Clovel** [comment]
Hi ! I am having the same issue and the given example doesn't fix it. 

Here is my `docker-compose.yml` file (extract)

```yml
  home-traefik:
    # The official v2 Traefik docker image
    image: traefik:latest
    container_name: "home-traefik"
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - '--providers.docker=true'
      - '--entryPoints.web.address=:80'
      - '--providers.docker.watch=true'
      - '--providers.docker.swarmmode=true'
      - '--providers.docker.exposedbydefault=false'
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
  home-registry:
    image: "registry:latest"
    container_name: "home-registry"
    restart: always
    expose:
      - 5000
    ports:
      - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Home Docker Registry"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      [REDACTED]
    labels:
      - "traefik.http.routers.home-registry.rule=path(`/docker-registry`)"
      - "traefik.http.services.home-registry.loadbalancer.server.port=5000"

  browser:
    image: klausmeyer/docker-registry-browser:latest
    # container_name: "home-registry-browser"
    environment:
      DOCKER_REGISTRY_URL: http://home-registry:5000
      RAILS_RELATIVE_URL_ROOT: /docker
      SCRIPT_NAME: /docker
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.browser.rule=PathPrefix(`/docker`)'
      - 'traefik.http.services.browser.loadbalancer.server.port=8080'
      
      - 'traefik.http.middlewares.browser-stripprefix.stripprefix.prefixes=/docker'
      - 'traefik.http.routers.browser.middlewares=browser-stripprefix@docker'
      - 'traefik.http.routers.browser.service=browser'
    network_mode: bridge
```

I get a "404 page not found" error when I try to access the registry browser.
