### ISSUE TITLE
Unable to browse repository; err.code="name unknown" 

### ISSUE THREAD

**Issue by GreyArea765** [klausmeyer/docker-registry-browser#323]
I have deployed docker registry and docker-registry-browser with the following docker-compose file:

```yaml
---
version: '2'

services:
    docker-registry:
        image: registry:2
        container_name: docker-registry
        ports:
            - 5000:5000
        restart: always
        volumes:
            - /var/lib/docker-registry:/var/lib/registry
    
    docker-registry-frontend:
        image: klausmeyer/docker-registry-browser
        container_name: docker-registry-frontend
        ports:
            - 8080:8080
        environment:
            DOCKER_REGISTRY_URL: "http://mydockerhost.local:5000"
            NO_SSL_VERIFICATION: 0
```

I see the welcome page but when I click the Browse Repositories button I don't see any content, even though I have pushed images to the repository.

There seems to be this error thrown from docker-registry;

```text
level=error msg="response completed with error" err.code="name unknown" err.detail=map[name:registry-host.json] err.message="repository name not known to registry" go.version=go1.11.2 http.request.host="mydockerhost.local:5000"
```

Full console output below:
[console_output.txt](https://github.com/klausmeyer/docker-registry-browser/files/5334750/console_output.txt)
