### ISSUE TITLE
NGINX configuration & subroute issue

### ISSUE THREAD

**Issue by Clovel** [klausmeyer/docker-registry-browser#371]
Hello, 

I can't seem to configure NGINX nor the app to use a sub-route. I am trying to use `https://<address>/browser` to access the Docker Registry browser.

If I go to `https://<address>/browser`, I get inexplicably redirected to a (obviously) non-existing route : `https://<address>/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser/repo/browser`

I read the previous issues on this matter to try and find a solution. 

I use Docker Compose to start the registry and the browser. 

# Docker Compose
(Extract only)
```yaml
  registry-browser:
    image: "klausmeyer/docker-registry-browser"
    container_name: "registry-browser"
    restart: always
    ports:
      - "8080:8080"
    environment:
      DOCKER_REGISTRY_URL: "http://registry:5000"
      ENABLE_DELETE_IMAGES: "true"
      SCRIPT_NAME: "/browser"
      RAILS_RELATIVE_URL_ROOT: "/browser"
```

# NGINX configuration
(Extract only)
```config
...
  # Docker Registry Browser
  location /browser {
    proxy_pass http://127.0.0.1:8080;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Port  443;
    proxy_set_header Authorization     "";

    proxy_redirect   off;
    sub_filter_types *;
    sub_filter_once  off;
    sub_filter       "/repo/" "/browser/repo/";
  }

  # Docker Registry V2 API
  location /v2/ {
...
```
