### ISSUE TITLE
Document using the app in a subPath

### ISSUE THREAD

**Issue by manelclos** [klausmeyer/docker-registry-browser#449]
Hi, here is an ingress and configmap for using docker-registry-browser in a subpath, in the same domain as the private registry, when using ingress-nginx. The rewrite is needed otherwise you get an infinite redirect.

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: docker-registry-browser
  namespace: docker-registry
spec:
  rules:
  - host: registry.example.com
    http:
      paths:
      - pathType: Prefix
        path: /browser/(.*)
        backend:
          service:
            name: docker-registry-browser
            port:
              number: 8080
```

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-browser
data:
  DOCKER_REGISTRY_URL: http://docker-registry:5000
  SCRIPT_NAME: "/browser"
  RAILS_RELATIVE_URL_ROOT: "/browser/"
```
