### ISSUE TITLE
Token based auth with Keycloak as IDP

### ISSUE THREAD

**Issue by dennismeissel** [klausmeyer/docker-registry-browser#553]
We are using Docker Registry Authentication with Keycloak.
In our configuration we have "docker"-feature enabled by Keycloak, in registry-config the issuer is the address of our Keycloak.
In this configuration our Keycloak users can login in Docker Registry using the command line.

I've entered TOKEN_AUTH_USER and TOKEN_AUTH_PASSWORD variables, but it doesn't work: 

```
Error
The obtained bearer token was rejected by the registry.

Please verify the ACLs to ensure the configured user has the required permissions.
Delete session cookies to retry.
```

Is it possible to use docker-registry-browser with Keycloak Authentication?

**Comment by klausmeyer** [comment]
The token based auth was only tested with https://github.com/dennismeissel/docker_auth and might be very specific to it.

We can keep this around as feature request and in case someone wants to work on it I'm happy to accept contributions.

**Comment by klausmeyer** [comment]
I just had some motivation to give it a try.

For me it is working fine - here my used config:

```yaml
services:
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_TLS_CERTIFICATE: /opt/certs/localhost.crt
      REGISTRY_HTTP_TLS_KEY: /opt/certs/localhost.key
      REGISTRY_AUTH_TOKEN_REALM: https://idp.home.klaus-meyer.net/auth/realms/home/protocol/docker-v2/auth
      REGISTRY_AUTH_TOKEN_SERVICE: docker-registry
      REGISTRY_AUTH_TOKEN_ISSUER: https://idp.home.klaus-meyer.net/auth/realms/home
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /opt/certs/localhost_trust_chain.pem
    volumes:
      - ./data:/data:z
      - ./certs:/opt/certs:z

  browser:
    image: klausmeyer/docker-registry-browser:latest
    ports:
      - 127.0.0.1:8080:8080
    environment:
      DOCKER_REGISTRY_URL: https://registry:5000
      ENABLE_DELETE_IMAGES: 'true'
      NO_SSL_VERIFICATION: 'true'
      PUBLIC_REGISTRY_URL: 'localhost:5000'
      TOKEN_AUTH_PASSWORD: 'admin'
      TOKEN_AUTH_USER: 'admin@example.com'
```

Is there anything related in the logs? Either from Registry, Keycloak or this app?
