### ISSUE TITLE
Can't run browser container

### ISSUE THREAD

**Issue by nba2023** [klausmeyer/docker-registry-browser#636]
Hi,
I follow this command, but there is no container running.
```
$ docker run --name registry-browser -p 8081:8080 klausmeyer/docker-registry-browser
Missing SECRET_KEY_BASE variable.
Generate a unique and strong value with: openssl rand -hex 64

$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND                  CREATED         STATUS                     PORTS     NAMES
87a7567248c0   klausmeyer/docker-registry-browser   "/docker-entrypoint.…"   6 seconds ago   Exited (1) 4 seconds ago             registry-browser
$ docker logs 87a
Missing SECRET_KEY_BASE variable.
Generate a unique and strong value with: openssl rand -hex 64
```
Someone can help me to fix it?

**Comment by nba2023** [comment]
It worked, but when start and browse `http://10.6.140.38:8081/`, return 500 error.
```
$ docker logs dd6
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.2.3-p157) ("The Eagle of Durango")
*  Min threads: 5
*  Max threads: 5
*  Environment: production
*          PID: 1
* Listening on http://0.0.0.0:8080
Use Ctrl-C to stop
I, [2024-05-14T09:37:11.107428 #1]  INFO -- : [6611ce7d-33a2-435c-87df-e699a6e834fb] Started GET "/" for 10.6.138.41 at 2024-05-14 09:37:11 +0000
I, [2024-05-14T09:37:11.109309 #1]  INFO -- : [6611ce7d-33a2-435c-87df-e699a6e834fb] Processing by RepositoriesController#index as HTML
I, [2024-05-14T09:37:11.143448 #1]  INFO -- request: [6611ce7d-33a2-435c-87df-e699a6e834fb] GET http://10.6.140.38:5000/v2/_catalog?n=100
I, [2024-05-14T09:37:11.184646 #1]  INFO -- : [6611ce7d-33a2-435c-87df-e699a6e834fb] Completed 500 Internal Server Error in 75ms (Allocations: 8210)
E, [2024-05-14T09:37:11.185828 #1] ERROR -- : [6611ce7d-33a2-435c-87df-e699a6e834fb]
[6611ce7d-33a2-435c-87df-e699a6e834fb] Faraday::BadRequestError (the server responded with status 400):
[6611ce7d-33a2-435c-87df-e699a6e834fb]
[6611ce7d-33a2-435c-87df-e699a6e834fb] app/models/repository.rb:7:in `list'
[6611ce7d-33a2-435c-87df-e699a6e834fb] app/controllers/repositories_controller.rb:12:in `index'
```
This is my docker-compose.yml:
```
version: '3.8'

services:
  registry-ui:
    image: klausmeyer/docker-registry-browser:1.7.2
    restart: always
    ports:
      - 8081:8080
    environment:
      DOCKER_REGISTRY_URL: http://10.6.140.38:5000
      SECRET_KEY_BASE: 4d75da8cfc8f22f273f636c7f554c6e2732428f9f4f2b4c6f1776d2289f8b7f795dab2b9d934a398482baf72e6b95f01dd129595573867e186c56dc75373c544
      NO_SSL_VERIFICATION: true
      TOKEN_AUTH_USER: docker
      TOKEN_AUTH_PASSWORD: swdq
        #SSL_CERT_PATH: '/auth/10.6.140.38.pem'
        #SSL_KEY_PATH: '/auth/10.6.140.38.key'
    volumes:
      - './auth:/auth:ro'


  registry-server:
    image: registry:2.8.3
    restart: always
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/10.6.140.38.pem
      REGISTRY_HTTP_TLS_KEY: /certs/10.6.140.38-key.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./db:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml
    ports:
      - '5000:5000'
    container_name: registry-server
```

**Comment by klausmeyer** [comment]
Your `registry-server` is returning an HTTP 400 (Bad Request) error.

Can you check what is returned for http://10.6.140.38:5000/v2/_catalog?n=100 in your browser?

**Comment by nba2023** [comment]
Hi, the result is as follows:
The browser refer to `http://10.6.140.38:5000/v2/_catalog?n=100` show `Client sent an HTTP request to an HTTPS server.`
After add nginx in docker-compose.yml
```
nginx:
    image: nginx:latest
    restart: always
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - registry-server
      - registry-ui
```
And nginx.conf
```
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream registry {
        server 10.6.140.38:5000;
    }

    server {
        listen 443 ssl;
        server_name 10.6.140.38;

        ssl_certificate /etc/nginx/certs/10.6.140.38.pem;
        ssl_certificate_key /etc/nginx/certs/10.6.140.38-key.pem;

        # disable any limits to avoid HTTP 413 for large image uploads
        client_max_body_size 0;

        # required to avoid HTTP 411: see Issue #1486 (https://github.com/docker/docker/issues/1486)
        chunked_transfer_encoding on;

        location / {
            proxy_pass http://10.6.140.38:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /v2/ {
            # Do not allow connections from docker 1.5 and earlier
            # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
            if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*\$" ) {
              return 404;
            }
            proxy_pass http://10.6.140.38:5000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # These headers are required for Docker to trust the registry
            # certificate and enable client-side certificate validation
            proxy_ssl_verify on;
            proxy_ssl_trusted_certificate /etc/nginx/certs/10.6.140.38.pem;
            proxy_ssl_session_reuse off;
        }
    }
}
```
Modify this part in `docker-compose.yml`
```
services:
  registry-ui:
    #image: joxit/docker-registry-ui:main
    #restart: always
    #ports:
    #  - 8081:80
    #environment:
    #  - SINGLE_REGISTRY=true
    #  - NGINX_PROXY_PASS_URL=http://10.6.140.38:5000
    #  - REGISTRY_TITLE=Docker Registry UI
    #  - DELETE_IMAGES=true
    #  - SHOW_CONTENT_DIGEST=true
    #  - SHOW_CATALOG_NB_TAGS=true
    #  - CATALOG_MIN_BRANCHES=1
    #  - CATALOG_MAX_BRANCHES=1
    #  - TAGLIST_PAGE_SIZE=100
    #  - REGISTRY_SECURED=false
    #  - CATALOG_ELEMENTS_LIMIT=1000
    #container_name: registry-ui
    image: klausmeyer/docker-registry-browser:1.7.2
    restart: always
    ports:
      - 8081:8080
    environment:
      DOCKER_REGISTRY_URL: https://10.6.140.38:5000
      SECRET_KEY_BASE:  sha-key
      NO_SSL_VERIFICATION: true
      TOKEN_AUTH_USER: username
      TOKEN_AUTH_PASSWORD: password
        #SSL_CERT_PATH: '/auth/10.6.140.38.pem'
        #SSL_KEY_PATH: '/auth/10.6.140.38.key'
    volumes:
      - './auth:/auth:ro'
    depends_on:
      - registry
```
Can access to `https://10.6.140.38:5000/v2/_catalog` and `http://10.6.140.38:8081/` can access too
