### ISSUE TITLE
There is no functionality to delete tags.

### ISSUE THREAD

**Issue by Firfr** [klausmeyer/docker-registry-browser#705]
我看文档介绍，是有删除镜像标签功能的，但是我安装后，没有镜像标签的删除的功能
According to the documentation, there is functionality to delete image tags, but after I installed it, I do not have the option to delete image tags.
部署版本 1.7.4
Deployment version 1.7.4

请问如何实现删除标签的功能，或者是没有这个功能了
May I ask how to achieve the functionality to delete tags, or has this feature been removed?

compose.yml
```yaml
services:
  registry-browser:
    container_name: registry-browser
    image: klausmeyer/docker-registry-browser:1.7.4
    network_mode: bridge
    restart: no
    # restart: always
    cpus: 1
    mem_limit: 512m
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      TZ: Asia/Shanghai
      TIME_ZONE: Asia/Shanghai
      SECRET_KEY_BASE: 6jk290vnmdkfj634h786dxfj76
      DOCKER_REGISTRY_URL: http://192.168.13.7:1023/v2
    ports:
      - 1045:8080
```

![2025-01-15_14-46-17](https://github.com/user-attachments/assets/cecb9b18-861b-42a7-9015-603feec8e894)

![2025-01-15_14-46-41](https://github.com/user-attachments/assets/6828a982-37aa-4fac-a78c-0176ae4dd881)
