### ISSUE TITLE
Delete not working behind proxy

### ISSUE THREAD

**Issue by bsimpson53** [klausmeyer/docker-registry-browser#9]
I've set up my registry and registry-browser behind haproxy (docker-flow-proxy) and I am terminating ssl on the proxy (and validating a client certificate) it works just fine except when deleting tags. I get the following message in the browser:

"The change you wanted was rejected."

In the server logs I see:

```
I, [2017-05-16T14:05:02.607865 #5]  INFO -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] Started DELETE "/repo/plugins/docker/tag/latest" for 10.0.1.18 at 2017-05-16 14:05:02 +0000
I, [2017-05-16T14:05:02.617338 #5]  INFO -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] Processing by TagsController#destroy as HTML
I, [2017-05-16T14:05:02.618123 #5]  INFO -- : [0da81994-4c18-40cb-bff5-d4280fb424fc]   Parameters: {"authenticity_token"=>"oVjTT0S2RrXg6jd6mHQrlUY476dTkw1Lf2A7rxWMrlV8bzCkEGxuzOxYit28oob4mR/UTizh96UG3jSYG88i5A==", "repo"=>"plugins/docker", "tag"=>"latest"}
W, [2017-05-16T14:05:02.620435 #5]  WARN -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] HTTP Origin header (https://registry-browser.mydomain.io) didn't match request.base_url (http://registry-browser.mydomain.io)
I, [2017-05-16T14:05:02.621991 #5]  INFO -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] Completed 422 Unprocessable Entity in 3ms
F, [2017-05-16T14:05:02.629045 #5] FATAL -- : [0da81994-4c18-40cb-bff5-d4280fb424fc]   
F, [2017-05-16T14:05:02.629414 #5] FATAL -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
F, [2017-05-16T14:05:02.629778 #5] FATAL -- : [0da81994-4c18-40cb-bff5-d4280fb424fc]   
F, [2017-05-16T14:05:02.630538 #5] FATAL -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] actionpack (5.1.1) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
```

This is the segment from my docker-compose.yml:

```
  registry-browser:
    image: klausmeyer/docker-registry-browser
    environment:
      - DOCKER_REGISTRY_URL=http://registry:5000
      - ENABLE_DELETE_IMAGES=true
      - NO_SSL_VERIFICATION=true
    deploy:
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=registry-browser.mydomain.io
        - com.df.port=8080
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.verifyClientSsl=true
    networks:
      - proxy
```

I'm guessing that this is rooted in this line from the logs:

```
W, [2017-05-16T14:05:02.620435 #5]  WARN -- : [0da81994-4c18-40cb-bff5-d4280fb424fc] HTTP Origin header (https://registry-browser.mydomain.io) didn't match request.base_url (http://registry-browser.mydomain.io)
```

Do I need to do some additional header rewriting, and should I need to (I've not needed to for other services)?
